### ISSUE TITLE
Unable to print out Ranger21 Optimizer

### ISSUE THREAD

**Issue by Interpause** [kozistr/pytorch_optimizer#118]
Unable to print out the optimizer:

```py
optimizer = Ranger21(model.parameters(), 1000)
print(optimizer)
```

```sh
    print(optimizer)
TypeError: 'str' object is not callable
```

I believe it is due to the `@property` decorator at https://github.com/kozistr/pytorch_optimizer/blob/edee3720fd7e5f396dd1ab74952762802b8f47ec/pytorch_optimizer/optimizer/ranger21.py#L132. The `__str__` dunder is supposed to be a function rather than a property.

**Comment by kozistr** [comment]
Hello, Thanks for the report!

you're right ``__str__`` method is supposed to be a function, it's my mistake. I'll fix it right away.

**Comment by kozistr** [comment]
now you can use [`v2.5.1`](https://github.com/kozistr/pytorch_optimizer/releases/tag/v2.5.1) with the fix.

Thank you!

**Comment by Interpause** [comment]
No problem, thanks for maintaining the optimizers.
