### ISSUE TITLE
get_chebyshev_schedule not working

### ISSUE THREAD

**Issue by aliencaocao** [kozistr/pytorch_optimizer#168]
when i call `get_chebyshev_schedule` with any integer value like `get_chebyshev_schedule(5)`, it will error on `return steps[perm]`: `IndexError: index 3 is out of bounds for axis 0 with size 3`

Am I using this wrongly?

**Comment by kozistr** [comment]
Thanks for the report. the usage is correct! 
Actually, the current implementation is brought from [here](https://github.com/lessw2020/Ranger21/blob/main/ranger21/chebyshev_lr_functions.py), and the formula seems okay (I just checked the paper), But needs to fix the implementation.
