### ISSUE TITLE
Prodigy: An Expeditiously Adaptive Parameter-Free Learner

### ISSUE THREAD

**Issue by sdbds** [kozistr/pytorch_optimizer#182]
Prodigy: An Expeditiously Adaptive Parameter-Free Learner
K. Mishchenko, A. Defazio
Paper: https://arxiv.org/pdf/2306.06101.pdf

official repository
https://github.com/konstmish/prodigy

**Comment by kozistr** [comment]
thanks! I'll look into it

**Comment by kozistr** [comment]
I just deployed a new version [v2.10.1](https://github.com/kozistr/pytorch_optimizer/releases/tag/v2.10.1) with Prodigy optimizer.

thanks for the suggestion!
