### ISSUE TITLE
Can a variant of Lion named Tiger be added to your package?

### ISSUE THREAD

**Issue by liujuncn** [kozistr/pytorch_optimizer#191]
## Tiger 
https://kexue.fm/archives/9512

<img width="466" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/902005/b5f36bd1-5b8b-4b10-a618-69ab6fc6f1b1">

<img width="528" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/902005/fe2e64e2-57d2-4d33-8549-9896a40ed24c">

You can use google translator to read this article.

Tensorflow implement: https://github.com/bojone/tiger

**Comment by kozistr** [comment]
sure! thanks for the request!

**Comment by kozistr** [comment]
now it's on the main branch!

thanks for the suggestion :)
