### ISSUE TITLE
sophiah bug

### ISSUE THREAD

**Issue by robotzheng** [kozistr/pytorch_optimizer#193]
File "/opt/conda/envs/dsd/lib/python3.10/site-packages/pytorch_optimizer/optimizer/sophia.py", line 92, in step
    self.compute_hutchinson_hessian(
  File "/opt/conda/envs/dsd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/dsd/lib/python3.10/site-packages/pytorch_optimizer/base/optimizer.py", line 100, in compute_hutchinson_hessian
    h_zs = torch.autograd.grad(grads, params, grad_outputs=zs, retain_graph=i < num_samples - 1)
  File "/opt/conda/envs/dsd/lib/python3.10/site-packages/torch/autograd/__init__.py", line 303, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by kozistr** [comment]
hi @robotzheng. could you share the reproducible code and environment info?

I suppose without knowing any info except the error, maybe `create_graph` needs to be set to `True` when backward the loss.

like this -> `loss.backward(create_graph=True)`

thank you!

**Comment by robotzheng** [comment]
in the code of https://github.com/booydar/LM-RMT

elif  args.optim.lower() == 'sophiah':
    optimizer = SophiaH(model.parameters(), lr=args.lr, betas=(0.96, 0.99), p = 0.01,  weight_decay=1e-1)

**Comment by kozistr** [comment]
> in the code of https://github.com/booydar/LM-RMT
> 
> elif args.optim.lower() == 'sophiah': optimizer = SophiaH(model.parameters(), lr=args.lr, betas=(0.96, 0.99), p = 0.01, weight_decay=1e-1)

well, if you use `train` function to train in `train.py` script, I guess `create_graph` issue is right.

there's no `create_graph=True` there https://github.com/booydar/LM-RMT/blob/main/pytorch/train.py#L516

**Comment by robotzheng** [comment]
thanks, it running

**Comment by kozistr** [comment]
> thanks, it running

great!

if you have any other questions & issues, feel free to re-open this issue or just tag me here :)

thank you
