### ISSUE TITLE
Adding the CAME optimizer

### ISSUE THREAD

**Issue by LiutongZhou** [kozistr/pytorch_optimizer#195]
## Paper or Code

Paper: CAME: Confidence-guided Adaptive Memory Efficient Optimization. ACL 2023 Outstanding Paper https://aclanthology.org/2023.acl-long.243/ 

Code: https://github.com/huawei-noah/Pretrained-Language-Model/tree/master/CAME

License: Apache 2.0

**Comment by kozistr** [comment]
I just merged the CAMe optimizer into the main branch! you can check the source code [here](https://github.com/kozistr/pytorch_optimizer/blob/main/pytorch_optimizer/optimizer/came.py)

thanks for the request!

**Comment by kozistr** [comment]
I just released a new version [v2.11.1](https://github.com/kozistr/pytorch_optimizer/releases/tag/v2.11.1). now `CAME` optimizer is available!
