### ISSUE TITLE
Empty Docs Sections

### ISSUE THREAD

**Issue by InfluxOW** [kozistr/pytorch_optimizer#204]
In the Docs, every section in every page is now empty. I tried different browsers and VPNs, it didn't solved an issue. Everything worked fine a few weeks ago.
<img width="868" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/57688681/cc78f81e-c8b4-42aa-a3a2-9b061ee3ea1e">
<img width="874" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/57688681/c7832672-8337-4292-a3b8-4c18997851ae">
<img width="832" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/57688681/804b823f-e367-4227-9f8d-28c254b25edc">
<img width="811" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/57688681/277e79d0-7cfd-4c4e-8635-43d9dfd53142">
<img width="828" alt="image" src="https://github.com/kozistr/pytorch_optimizer/assets/57688681/1edb3a5a-fc14-4871-8f53-3109dfcab2d4">

**Comment by kozistr** [comment]
thanks for the report! I'll look into it. that's weird though. maybe there's an typo in docs or build issue i guess.

**Comment by kozistr** [comment]
I found an issue. it's because of the `sphinx` version. The current config works with `sphinx 6.x`, but recently, `sphinx 7` has been out and seems incompatible with the previous config i guess.

**Comment by kozistr** [comment]
@InfluxOW fixed! you can check the docs normally now :) -> https://pytorch-optimizers.readthedocs.io/en/latest/base_api.html

thanks again

**Comment by InfluxOW** [comment]
@kozistr Great work! Thanks for fixing it so fast!

**Comment by kozistr** [comment]
fyi) I just migrated from `sphinx` to `mkdocs` with `material` theme. the difference is that it looks cleaner and fancy!

![image](https://github.com/kozistr/pytorch_optimizer/assets/15344796/5cfe664e-5973-4421-9c41-3d8e20fdfa38)

**Comment by InfluxOW** [comment]
Looks great, much more readable and clear! Hope it won't break with new update :)
