### ISSUE TITLE
Improvement to SAM: SAM as an Optimal Relaxation of Bayes

### ISSUE THREAD

**Issue by redknightlois** [kozistr/pytorch_optimizer#212]
## SAM as an Optimal Relaxation of Bayes

> Sharpness-aware minimization (SAM) and related adversarial deep-learning methods can drastically improve generalization, but their underlying mechanisms are not yet fully understood. Here, we establish SAM as a relaxation of the Bayes objective where the expected negative-loss is replaced by the optimal convex lower bound, obtained by using the so-called Fenchel biconjugate. The connection enables a new Adam-like extension of SAM to automatically obtain reasonable uncertainty estimates, while sometimes also improving its accuracy. By connecting adversarial and Bayesian methods, our work opens a new path to robustness

Preprint: https://arxiv.org/abs/2210.01620

![image](https://github.com/kozistr/pytorch_optimizer/assets/1045411/d093075b-05c3-4c4e-ac9e-cefea92fc776)

**Comment by kozistr** [comment]
thanks for the suggestion! I'll check it soon : )
