### ISSUE TITLE
Aida optimizer

### ISSUE THREAD

**Issue by okbalefthanded** [kozistr/pytorch_optimizer#220]
A new optimizer that improves upon AdaBelief is proposed in this paper [Aida](https://openreview.net/pdf?id=VI2JjIfU37) ,  the optimizer was tested against SGD, Adam, AdamW, Radam, Fromage, and AdaBelief on ResNet, Transformer, and LSTM. 

- Code : [Aida Code](https://github.com/guoqiang-zhang-x/Aida-Optimizer)

**Comment by kozistr** [comment]
thanks for the suggestion :) I'll check it

**Comment by kozistr** [comment]
now you can check the implementation on the latest `main` branch :)

**Comment by okbalefthanded** [comment]
@kozistr Thanks for fast addition.
