### ISSUE TITLE
Add WeLore

### ISSUE THREAD

**Issue by rotem154154** [kozistr/pytorch_optimizer#262]
Hi,

I really appreciate your work. For me, GaLore has worked the best out of all the optimizers. Could you please consider adding WeLore? It looks promising: https://arxiv.org/abs/2407.11239

Thank you!

**Comment by kozistr** [comment]
thanks i'll check it later!

**Comment by kozistr** [comment]
@rotem154154 sorry for the late reply. I just checked out the paper and it looks like it's not an optimizer, more like some tools for rank reduction. Also, their implementation only supports the specific parameters depending on the architecture such as LLaMa2 7/13B.

So, I guess it'd be good to wait until they support the model-agnostic parameters and make it easier to use.
