### ISSUE TITLE
ADOPT has an important stability update

### ISSUE THREAD

**Issue by ogencoglu** [kozistr/pytorch_optimizer#296]
https://github.com/iShohei220/adopt?tab=readme-ov-file#update-on-nov-22-2024

Can it be added?

**Comment by kozistr** [comment]
@ogencoglu hi! actually, I implemented that feature here #294 and it'll be included next release v3.3.0. thank you!

**Comment by ogencoglu** [comment]
Understood. Cheers!

**Comment by kozistr** [comment]
@ogencoglu just to let you know, I just deployed a new version `v3.3.0`, which includes the `ADOPT` optimizer with the stability update!
