### ISSUE TITLE
[Optimizer] MicroAdam

### ISSUE THREAD

**Issue by 67372a** [kozistr/pytorch_optimizer#299]
Wanted to make you aware of a potential optimizer of interest to add.

Paper: https://arxiv.org/abs/2405.15593
Code: https://github.com/IST-DASLab/MicroAdam

**Comment by kozistr** [comment]
@67372a thanks for the resources.

I looked into both the paper and implementation and found that `MicroAdam` requires [custom cuda kernels](https://github.com/IST-DASLab/ISTA-DASLab-Optimizers/tree/main/kernels) to run effectively, which would be slow in pure Python implementation.

Here's also from the MicroAdam paper chap 3.1.
> A direct implementation (e.g., in Pytorch) of the previous algorithm would not bring significant
benefits, and would in fact might slow down optimization in terms of wall-clock time. To realize the
theoretical gains, we detail a GPU-aware implementation below.

So, I think it's kind of complicated to implement it (or copy the whole baseline) here. Thus, maybe I could only add it to the README for now.

anyway, thanks for letting me know!
