### ISSUE TITLE
Scalable Second Order Optimization for Deep Learning

### ISSUE THREAD

**Issue by redknightlois** [kozistr/pytorch_optimizer#93]
I have been using your optimizers and I stumbled upon improvements on Shampoo. Just in case you havent seen them already.

Paper preprints: https://arxiv.org/abs/2002.09018

```
@misc{anil2021scalable,
      title={Scalable Second Order Optimization for Deep Learning},
      author={Rohan Anil and Vineet Gupta and Tomer Koren and Kevin Regan and Yoram Singer},
      year={2021},
      eprint={2002.09018},
      archivePrefix={arXiv},
      primaryClass={cs.LG}
}
```

Pytorch implementation is slower than the JAX implementation as it is written with readability than speed in mind. https://github.com/google-research/google-research/tree/master/scalable_shampoo

**Comment by kozistr** [comment]
thanks for the reference and suggestion!

I agree that the JAX implementation is faster than Pytorch, however, the project's goal is specifically to implement the optimizer using Pytorch. Despite this, there are features that have yet to be developed, such as Grafting and Partitioning. I'll add these features to improve the Shampoo optimizer.

best regard :)

**Comment by kozistr** [comment]
I re-implemented Shampoo optimizer based on your linked code and deployed the package (v2.3.0)! If there're any ideas and requests, feel free to leave a comment or open another issue :)

thanks!

**Comment by redknightlois** [comment]
I will give it a try.
